project:
  type: website
  resources:
    - files/resume.pdf
  output-dir: docs

website:
  title: "Raine Higa"
  site-url: https://www.rainehiga.com
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
